services:
  postges:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: chis
      POSTGRES_PASSWORD: chis
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - bsn_network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080  # For UI
      - 1025:1025  # For SMTP server
    networks:
      - bsn_network

  bsn-api: # Backend container
    container_name: bsn-api
    image: bsn/bsn:0.0.1
    ports:
      - 8088:8088
    networks:
      - bsn_network
    depends_on:
      - postges # When postgres is up and running then we start our backend container

networks:
  bsn_network:
    driver: bridge

volumes:
  postgres:
    driver: local