spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: chis
    password: chis
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate will automatically update the database schema to match the entity classes. Only for dev
    show-sql: false
    properties:
      hibernate:
        format_sql: true  # Hibernate will print the SQL statements in a more human-readable format
    database: postgresql  # This helps Hibernate understand how to interact with the database correctly.
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # The dialect defines how Hibernate should communicate with the database, including SQL syntax and data types.

  mail:
    host: smtp.gmail.com # smtp.gmail.com instead of localhost for production
    port: 465 # 465 instead of 1025
    username: some_email_user@gmail.com
    password: some_generated_password # Generated password in Gmail App passwords
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp

application:
  security:
    jwt:
      secret-key: 291d7b170fc96c6d87eed5d2fdf437eb20d508cc854cd34405818281c754bdab
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

server:
  port: 8088